### ISSUE TITLE
Cannot concatenate tasks because of return value?

### ISSUE THREAD

**Issue by ghost** [php-taskman/github#7]
Hi Pol,

I'm trying to concatenate tasks in a single command in taskman.yml.dist.

```yml
commands:
    build:release:
        tasks:
            - { task: "github.release.create", user: "verbruggenalex", project: "example-drupal-project", tag: ~ token: ~ }
            - { task: "github.asset.upload", user: "verbruggenalex", project: "example-drupal-project", tag: ~, token: ~, file: "composer.json" }
        options:
            tag:
                description: The release tag.
                mode: 2
            token:
                description: The github api token.
                mode: 2
```

But when executing the command it stops after the first task execution of github.release.create.

>  [PhpTaskman\Github\Plugin\Task\ReleaseCreateTask] Release has been created.
 [PhpTaskman\Github\Plugin\Task\ReleaseCreateTask]   
 [PhpTaskman\Github\Plugin\Task\ReleaseCreateTask]  Exit code 0 

It seems like the return statement is preventing the second task from executing. When I comment out the return statement from the task the secondary task is also executed:
https://github.com/php-taskman/github/blob/master/src/Plugin/Task/ReleaseCreateTask.php#L67

Do we really need to return that value in these tasks?
